//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDN
    {
        public Nullable<int> soluong { get; set; }
        public string MaHDN { get; set; }
        public string MaMT { get; set; }
        public Nullable<double> thanhtien { get; set; }
    
        public virtual Hoadonnhap Hoadonnhap { get; set; }
        public virtual ThongTinMayTinh ThongTinMayTinh { get; set; }
    }
}
