//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonnhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoadonnhap()
        {
            this.ChiTietHDNs = new HashSet<ChiTietHDN>();
        }
    
        public string MaHDN { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> Ngayban { get; set; }
        public Nullable<double> Tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDN> ChiTietHDNs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
