//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinMayTinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinMayTinh()
        {
            this.ChiTietHDBs = new HashSet<ChiTietHDB>();
            this.ChiTietHDNs = new HashSet<ChiTietHDN>();
        }
    
        public string MaMT { get; set; }
        public string tenmt { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> giaban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDB> ChiTietHDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDN> ChiTietHDNs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
